[package]
name = "ub2cb_bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ub2cb"
path = "src/main.rs"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ub2cb = { path = ".." }
